sudo: false
language: java

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

jdk:
  - openjdk8
  - openjdk9
  - openjdk10
  - openjdk11
  - openjdk-ea
  - oraclejdk8
  - oraclejdk9
  - oraclejdk11

matrix:
  fast_finish: true
  allow_failures:
    - jdk: oraclejdk11